server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/explain?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: root
    password: root
#mybatis:配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.bean    # 所有pojo别名类所在包
redisson:
  address: redis://127.0.0.1:6379
